### ISSUE TITLE
All-in-one class framework or Stub classes into their own branch?

### ISSUE THREAD

**Issue by yevdev** [Schaka/VanillaFightclassFramework#4]
The code base allows for combat helpers, lua snippets, and overall quality of life convenience for making Fight Classes.

Do we want to create this to be an all-in-one class similar to how Singular was to HB?
Or would it make sense to stub a dummy branch per class, and merge down from master into the feature branch for a class.

- /master (PR all core functionality changes)
- /Warlock (Pull from master, make sure it's at the same commit #)
- /Rogue (Pull from master, make sure it's at the same commit #)
- ...eg

**Comment by Schaka** [comment]
I'd prefer providing an all-in-one framework that allows support for every single class (and keep the simplified fightclass implementation that currently uses mage spells), without actually publishing too much dummy fightclasses.

My main concern is that if we make it too easy, armchair developers will compile it and run fightclasses as they are. Which can go two ways:

1. people will spam us for support requests, which will be annoying to say the least
2. mediocre or even good fightclasses become the norm, but being exactly identical will lead to easy pattern recognizion and increases overall ban rates

**Comment by Lbniese** [comment]
I like it's current state. A framework which can be used for any class with a simple rotation example (The mage one).

People should be able to edit the framework themselves to change rotation / support other classes in my opinion.
